### PR TITLE
[Bug] Fixed loading urls with query params

### LINKED ISSUE #765: [Bug] Getting error message after upgrading from version 1.1.3 to 1.1.8
**Describe the bug**
My application still works fine on version 1.1.3 but after upgrading to version 1.1.8, I had some errors.
**Screenshots**
image

**Additional context**
If I change that line `var mapState = config.mapState;` to `var mapState = config && config.mapState;`, my application will work but very laggy. Please help me to resolve this issue. Thank you

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 77.0.3865.90 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by macrigiuseppe**
It won't remove the current logic, URLs must still include '.csv' and '.json' but it will allow the usage of query parameters

Signed-off-by: Giuseppe Macri <gmacri@uber.com>

### CODE REVIEW

File: examples/demo-app/src/utils/url.js [hunk 1]
```diff
@@ -39,3 +39,45 @@ export function parseQueryString(query) {
 export function getMapPermalink(mapLink) {
   return `${window.location.protocol}//${window.location.host}/${MAP_URI}${mapLink}`
 }
+
+// from http://blog.stevenlevithan.com/archives/parseuri
+/**
+ * Allows to break down a url into multiple params
+ * @param str
+ */
+export function parseUri (str) {
```
Comment (heshan0131) [inline examples/demo-app/src/utils/url.js]: There is a nice little library that does this
https://www.npmjs.com/package/query-string

Comment (macrigiuseppe) [reply examples/demo-app/src/utils/url.js]: I look into the library, unfortunately it can only parse the query param part of URI.

I wanted something like: 
parse(http://www.whatever.com/index.csv?param1=1&param2=2 and return something)

```
{
  host: www.whatever.com,
  file: index.csv,
  params: {
    param1=1,
    param2=2
  }
}
```

Comment (heshan0131) [reply examples/demo-app/src/utils/url.js]: I don't get it, isn't your `mapUrl=file.csv` also part of the query param?

File: examples/demo-app/src/actions.js [hunk 2]
```diff
@@ -30,6 +30,7 @@ import {
 import {LOADING_METHODS_NAMES} from './constants/default-settings';
 import {CLOUD_PROVIDERS} from './utils/cloud-providers';
 import {generateHashId} from './utils/strings';
+import { parseUri } from './utils/url';
```
Comment (heshan0131) [inline examples/demo-app/src/actions.js]: delete space in bracket
