### PR TITLE
[Bug] Fixed issue with geojson fields

### LINKED ISSUE #679: [Bug] Table view crashes when geojson dataset is being display
https://kepler.gl/demo/nyc_census

Datatable view crashes

### PR DESCRIPTION
**Pull request by macrigiuseppe**
Fixes #679 

The current implementation doesn't have the ability to display a subset of the row properties so I had to create a way to omit some of the properties.

Signed-off-by: Giuseppe Macri <gmacri@uber.com>

679-table-issue

### CODE REVIEW

File: src/components/modals/data-table-modal.js [hunk 1]
```diff
@@ -90,8 +90,19 @@ function DataTableModalFactory(DataGrid) {
     const activeDataset = datasets[dataId];
     const rows = activeDataset.data;
 
-    const columns = activeDataset.fields
-      .filter(({name}) => name !== '_geojson');
+    const {columns, dataColumnMap} = activeDataset.fields.reduce((acc, field, index) => {
+      const valid = field.name !== '_geojson';
```
Comment (heshan0131) [inline src/components/modals/data-table-modal.js]: We can add a function to parse `_geojson` field instead of filter them out. 
I think it's useful to display it, especially when people uploaded csv contains `WKT` and `Feature`. Put it in `data-utils` maybe, so it can be used in other places

```js
const parseFieldValue = (value, type) => {

  if (!notNullorUndefined(value)) {
    return '';
  }

  switch (type) {
    case ALL_FIELD_TYPES.boolean:
      return String(value);
    case ALL_FIELD_TYPES.geojson:
      return typeof value === 'string' ? value :
      isPlainObject(value) ? JSON.stringify(value) :
      Array.isArray(value) ? `[${String(value)}]` : '';
    default:
      return value;
  }
}
```

File: src/components/common/datagrid.js [hunk 2]
```diff
@@ -90,9 +90,13 @@ const StyledCell = styled.div`
   height: 100%;
 `;
 
-const CellTemplate = ({name, type}) => {
-  const value = type === ALL_FIELD_TYPES.boolean ? String(name) : name;
-  return (<StyledCell title={value}><span>{value}</span></StyledCell>);
+const CellTemplate = ({value, type}) => {
+  const content = type === ALL_FIELD_TYPES.boolean ? String(value) : value;
+  return (
+    <StyledCell title={content}>
```
Comment (heshan0131) [inline src/components/common/datagrid.js]: why `title`?

File: src/components/common/datagrid.js [hunk 3]
```diff
@@ -90,9 +90,13 @@ const StyledCell = styled.div`
   height: 100%;
```
Comment (heshan0131) [inline src/components/common/datagrid.js]: when `span` is in `StyledCell` text-overflow css needs to be applied to `span`, instead of the parent `div`
```
  span {
    overflow: scroll;
    text-overflow: ellipsis;
    white-space: pre-wrap;
    word-wrap: break-word;
    width: 100%;
  }
```

File: src/components/common/datagrid.js [hunk 4]
```diff
@@ -125,12 +129,19 @@ function DataGridFactory(
 
       const type = columns[columnIndex].type;
 
+      let content = null;
+      if (rowIndex) {
+        const {dataColumnMap = {}} = this.props;
+        const dataIndex = dataColumnMap[columnIndex] !== null || dataColumnMap[columnIndex] !== undefined
+          ? dataColumnMap[columnIndex] : columnIndex;
+        content = (<Cell className={`cell ${type}`} value={rows[rowIndex - 1][dataIndex]} type={type} />);
```
Comment (heshan0131) [inline src/components/common/datagrid.js]: `className` here will not be displayed, because you are not rendering it in `Cell`

File: src/components/common/datagrid.js (hunk 3 above)
Comment (heshan0131) [reply src/components/common/datagrid.js]: Also maybe add left padding to the first cell
```
const DataGridWrapper = styled.div`
   .....other css
  .ReactVirtualized__Grid {
    .column-0 .cell{
      padding-left: 24px;
    }
  }
```

File: src/components/common/datagrid.js [hunk 5]
```diff
@@ -90,9 +90,13 @@ const StyledCell = styled.div`
...
+const CellTemplate = ({value, type}) => {
+  const content = type === ALL_FIELD_TYPES.boolean ? String(value) : value;
+  return (
+    <StyledCell title={content}>
+      <span>{content}</span>
+    </StyledCell>
+  );
 };
 
 export const CellFactory = () => CellTemplate;
```
Comment (heshan0131) [inline src/components/common/datagrid.js]: this could cause compile and uglify error

```js
export const CellFactory = () => {
const CellTemplate = ({value, type}) => {}
return CellTemplate
}

```

File: src/components/common/datagrid.js (hunk 2 above)
Comment (macrigiuseppe) [reply src/components/common/datagrid.js]: title will add the tooltip effect on mouse hover

File: src/components/common/datagrid.js (hunk 4 above)
Comment (macrigiuseppe) [reply src/components/common/datagrid.js]: fixed

File: src/components/common/datagrid.js (hunk 5 above)
Comment (macrigiuseppe) [reply src/components/common/datagrid.js]: fixed

**Comment by macrigiuseppe** [comment]
@heshan0131 updated with your comments and made a small change to make geojson columns easier to read.

### Non-geojson columns
679-table-issue

### Geojson Columns
679-table-issue

File: src/components/common/datagrid.js [hunk 6]
```diff
@@ -115,29 +148,42 @@ function DataGridFactory(
...
+      columns.some(c => c.type === ALL_FIELD_TYPES.geojson)
+    );
+
     _cellRenderer = ({columnIndex, key, rowIndex, style}) => {
       const {columns, rows} = this.props;
 
+      const isLast = columnIndex === columns.length - 1;
+
       // rowIndex -1 because data rows start rendering at index 1 and we normalize back using the -1 param
       const className = `${rowIndex === 0
```
Comment (heshan0131) [inline src/components/common/datagrid.js]: you can use `classnames` to construct this, easier to follow
```js
      const className = classnames(`column-${columnIndex}`, {
        last: isLast,
        [`header-${columnIndex}`]: rowIndex === 0,
        [`row-${rowIndex-1}}`]: rowIndex > 0
      });```

Comment (macrigiuseppe) [reply src/components/common/datagrid.js]: definitely better
